version: '3'

# Define services
services:

  # App Service
  app:
    container_name: iitk_coin
    image: golang/iitk_coin
    build:
        context: . # Use an image built from the specified dockerfile in the current directory.
        dockerfile: Dockerfile.multistage
    ports:
        - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine